(function(){var a=window;a.dT_?a.console&&a.console.log("Duplicate agent injection detected, turning off redundant initConfig."):window.dT_||(window.dT_={cfg:"#CONFIGSTRING#|auto=#AUTO#|domain=#DOMAIN#|rid=RID_#REQUEST_ID#|rpid=#RESPONSE_ID#|app=#APP#"})})();
(function(){function t(){var a=0;try{a=window.performance.timing.navigationStart+Math.floor(window.performance.now())}catch(b){}return 0>=a?(new Date).getTime():a}function T(a,b){return U(a,b)}function l(a,b){for(var c=1;c<arguments.length;c++)a.push(arguments[c])}function u(a,b){return parseInt(a,b||10)}function V(a){try{if(v)return v[a]}catch(b){}return null}function W(a,b){try{window.sessionStorage.setItem(a,b)}catch(c){}}function m(a,b){var c=-1;b&&(a&&a.indexOf)&&(c=a.indexOf(b));return c}function F(a){document.cookie=
a+'="";path=/'+(d.domain?";domain="+d.domain:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT;"}function G(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var h=a.charAt(c),d=X[h];d?l(b,d):l(b,h)}return b.join("")}function w(a,b,c,h){b||0==b?(b=(""+b).replace(/[;\n\r]/g,"_"),b="DTSA"===a.toUpperCase()?G(b):b,a=a+"="+b+";path=/"+(d.domain?";domain="+d.domain:""),c&&(a+=";expires="+c.toUTCString()),h&&(a+=";Secure"),document.cookie=a):F(a)}function r(a){var b,c,h,d=document.cookie.split(";");
for(b=0;b<d.length;b++)if(c=m(d[b],"="),h=d[b].substring(0,c),c=d[b].substring(c+1),h=h.replace(/^\s+|\s+$/g,""),h===a)return"DTSA"===a.toUpperCase()?decodeURIComponent(c):c;return""}function H(a){return/^[0-9A-Za-z_\$\+\/\.\-\*%\|]*$/.test(a)}function I(){var a=r(x);return a&&H(a)?a:""}function Y(a){w(x,a,void 0,!!d.ssc)}function J(a){a=a||I();var b={sessionId:null,serverId:null};if(a){var c=m(a,"|"),d=a;-1!==c&&(d=a.substring(0,c));c=m(d,"$");-1!==c?(b.sessionId=d.substring(c+1),b.serverId=d.substring(0,
c)):b.sessionId=d}return b}function Z(a){return J(a).serverId}function $(a){if(a)return J(a).sessionId;if(a=e.gSC()){var b=a.indexOf("|");-1!==b&&(a=a.substring(0,b))}return a}function K(a,b){return Math.floor(Math.random()*(b-a+1))+a}function aa(a){var b=window.crypto||window.msCrypto,c;if(b)c=new Int8Array(a),b.getRandomValues(c);else{c=[];for(b=0;b<a;b++)c.push(K(0,L))}a=[];for(b=0;b<c.length;b++){var d=Math.abs(c[b]%L),d=9>=d?String.fromCharCode(d+48):String.fromCharCode(d+55);a.push(d)}return a.join("")}
function M(a){return document.getElementsByTagName(a)}function N(a){var b=a.length;if("number"===typeof b)a=b;else{for(var b=0,c=2048;a[c-1];)b=c,c+=c;for(var d=7;1<c-b;)d=(c+b)/2,a[d-1]?b=d:c=d;a=a[d]?c:b}return a}function ba(){var a=d.csu,a=(a.indexOf("dbg")==a.length-3?a.substr(0,a.length-3):a)+"_"+d.app+"_Store";try{if(y){var b=y.getItem(a);if(b){for(var a={},c=b.split("|"),b=0;b<c.length;b++){var e=c[b].split("=");2==e.length&&(a[e[0]]=decodeURIComponent(e[1]))}z(a);if(!d.lastModification||parseInt(a.lastModification.substr(0,
13),10)>=parseInt(d.lastModification.substr(0,13),10))for(var q in a)a.hasOwnProperty(q)&&("config"==q?(A(a[q]),z(d)):d[q]=a[q])}}}catch(g){}}function A(a){a=a.split("|");for(var b=0;b<a.length;b++){var c=m(a[b],"=");-1===c?d[a[b]]="1":d[a[b].substring(0,c)]=a[b].substring(c+1,a[b].length)}}function ca(a,b){if(a){var c=/([a-zA-Z]*)[0-9]{0,3}_[a-zA-Z_0-9]*_[0-9]+/g.exec(a);if(c&&c.length){var h=c[0];d.csu=c[1];c=h.split("_");d.legacy="1";d.featureHash=c[1];d.dtVersion=e.version[0]+""+e.version[1]}}b&&
A(b);c=location.hostname;h=d.domain;c=c&&h?c==h||-1!==c.indexOf("."+h,c.length-("."+h).length)?!0:!1:!0;c||(delete d.domain,d.domainOverride="true")}function da(){return x}function ea(){return fa}function ga(){return ha}function B(a){d[a]=0>m(d[a],"#"+a.toUpperCase())?d[a]:""}function z(a){var b=a.spc;if(b){var c=document.createElement("textarea");c.innerHTML=b;a.spc=c.value}}function ia(){return s}function O(a,b){for(var c=P(b),d=!1,e=0;e<c.length;e++)c[e].frameId===s&&(c[e].actionId=a,d=!0);d||
l(c,{frameId:s,actionId:a});Q(c)}function Q(a,b){var c="";if(a){for(var c=[],d=0;d<a.length;d++)0<d&&0<c.length&&l(c,"p"),l(c,a[d].frameId),l(c,"h"),l(c,a[d].actionId);c=c.join("")}c||(c="-");w(C,c)}function P(a){var b=r(C),c=[];if(b&&"-"!==b)for(var b=b.split("p"),d=0;d<b.length;d++){var e=b[d].split("h");if(2===e.length&&e[0]&&e[1]){var g=e[0],f;if(!(f=a)){f=g.split("_");f=u(f[0]);var k=t()%D;k<f&&(k+=D);f=f+9E5>k}f&&l(c,{frameId:g,actionId:e[1]})}}return c}var g=window;if(!g.dT_||!g.dT_.cfg||"string"!=
typeof g.dT_.cfg||g.dT_.initialized)g.console&&g.console.log("Initconfig not found or agent already initialized! This is an injection issue.");else{var U=window.setTimeout,v=window.sessionStorage,e={version:[6,5,24,"1006"],cfg:window.dT_&&window.dT_.cfg,ica:1};e.version[3]=parseInt(e.version[3],10);window.dT_=e;e.agentStartTime=t();e.nw=t;e.apush=l;e.st=T;var L=32,X={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"};e.gSSV=V;e.sSSV=W;e.pn=u;e.iVSC=H;e.io=m;e.dC=
F;e.sC=w;e.esc=G;e.gSId=Z;e.gDtc=$;e.gSC=I;e.sSC=Y;e.gC=r;e.cRN=K;e.cRS=aa;e.gEL=N;e.gEBTN=M;var d={reportUrl:"dynaTraceMonitor",initializedModules:"",csu:"dtagent",domainOverride:"false",dataDtConfig:e.cfg},y;try{y=window.localStorage}catch(ja){}if(-1==m(d.dataDtConfig,"#CONFIGSTRING")&&(A(d.dataDtConfig),B("domain"),B("auto"),B("app"),(g=d.agentUri)&&-1<m(g,"_")))g=/([a-zA-Z0-9]*)[0-9]*_([a-zA-Z0-9]*)_[0-9]*/.exec(g),d.csu=g[1],d.featureHash=g[2],d.dtVersion=e.version[0]+""+e.version[1],z(d);var g=
M("script"),R=N(g);if(0<R)for(var k,S=d.csu+"_bootstrap.js",E=0;E<R;E++)if(k=g[E],k.attributes){var n=k.attributes.getNamedItem("data-dtconfig");k=k.src;if(n){ca(k,n.value);break}if((n=k&&k.indexOf(S))&&0<=n)n=n+S.length+5,d.app=k.length>n?k.substr(n):"Default%20Application"}ba();try{var f=d.ign;if(f&&RegExp(f).test(window.location.href)){document.dT_=window.dT_=null;return}}catch(ka){}var C="dtPC",x="dtCookie",fa="x-dtPC",ha="x-dtReferer";e.gSCN=da;e.gPCHN=ea;e.gRHN=ga;e.pageContextCookieName=C;
e.latencyCookieName="dtLatC";e.cfg=d;var D=6E8,s=e.agentStartTime%D+"_"+u(1E3*Math.random());e.gFId=ia;e.frameId=s;O(1);e.gPC=P;e.cPC=O;e.sPC=Q;var p;try{p=v.getItem("dtDisabled")}catch(la){}!d.auto&&(!d.legacy&&!p)&&(f=d.agentname||d.csu||"dtagent",f=r("dtUseDebugAgent")?d.debugName||f+"dbg":d.name||f,p=d.agentUri||d.agentLocation+"/"+f+"_"+d.featureHash+"_"+d.buildNumber,d.async?(f=document.createElement("script"),f.setAttribute("src",p),d.async&&f.setAttribute("defer","true"),f.setAttribute("crossorigin",
"anonymous"),p=document.getElementsByTagName("script")[0],p.parentElement.insertBefore(f,p)):document.write('<script type="text/javascript" src="'+p+'">\x3c/script>'))}})();
(function(){function V(){if("string"!==typeof document.title){var a=ka("title")[0];return a.innerText||a.textContent}return document.title}function Va(){return Wa?new Wa:Xa?new Xa("MSXML2.XMLHTTP.3.0"):q.XMLHttpRequest?new q.XMLHttpRequest:new q.ActiveXObject("MSXML2.XMLHTTP.3.0")}function Nb(a){if(a){var b=a.indexOf("lastModification=");if(0<=b)try{return parseInt(a.substring(b+17),10)}catch(c){}}return 0}function td(){return v}function Ob(){var a=document.location;return a?0===u(a.href,"file"):
!1}function ud(a){return!a||1!==a.length||"undefined"===typeof l.featureHash?!1:-1!==u(l.featureHash,a)}function vd(a){var b=q.dT_;if(b.ism(a)&&-1===u(b.iMod(),a))return b.iMod(a),!0;b.ism(a)&&q.console&&q.console.log("WARNING: "+('Module "'+a+'" already enabled!'));return!1}function wd(a){a&&(l.initializedModules+=a);return l.initializedModules}function xd(a){return l[a]}function yd(a,b){l[a]=b}function zd(a,b){var c=l[a]?F(l[a],10):b;return null==c||isNaN(c)?b:c}function Ad(a){var b;if("object"==
typeof a){b=[6,3,0,0];for(var c=0;c<b.length;c++){if(a[c]<b[c])return!1;if(a[c]>b[c])break}return!0}return a&&383<=a}function Bd(){return l.csu}function Cd(){if(l.xb){var a=Pb(l.xb);try{l.xbp=RegExp(a)}catch(b){}}}function Ha(a){return a?String.trim?a.trim():a.replace(/^\s+|\s+$/g,""):null}function Ya(a,b){if(a.indexOf)return a.indexOf(b);for(var c=a.length;c--;)if(a[c]===b)return c;return-1}function W(a,b,c){a==q?Qb?Qb(b,c,!0):Za&&Za("on"+b,c):a.addEventListener?a.addEventListener(b,c,!0):a.attachEvent&&
a.attachEvent("on"+b,c);for(var d=!1,f=Q.length;0<=--f;){var e=Q[f];if(e.object===a&&e.event===b&&e.handler===c){d=!0;break}}d||x(Q,{object:a,event:b,handler:c})}function Rb(a,b,c){for(var d=Q.length;0<=--d;){var f=Q[d];if(f.object===a&&f.event===b&&f.handler===c){Q.splice(d,1);break}}a==q?Sb?Sb(b,c,!0):Dd&&Za("on"+b,c):a.removeEventListener?a.removeEventListener(b,c,!0):a.detachEvent&&a.detachEvent("on"+b,c)}function $a(a){try{var b=a.tagUrn;return b&&-1!==u(b,"schemas-microsoft-com:vml")}catch(c){return!0}}
function Tb(a){if(!a||-1===a.indexOf("://"))return null;a=a.split("/")[2].split(":")[0].toLowerCase();return/^[^<>%/\\\(\)\{\}\[\] ]+$/.test(a)?a:null}function Ed(a){a=a?a:q.location.pathname;var b=q.location.search;b&&(b.length&&"?"===b.charAt(0))&&(b=b.substring(1));a=31+Ub(a);a=31*a+Ub(b);return"RID_"+(a&a)}function Ub(a){var b=0;if(a)for(var c=a.length,d=0;d<c;d++)b=31*b+a.charCodeAt(d),b&=b;return b}function ab(a,b){try{q.sessionStorage[a]=b}catch(c){la(a,b)}}function Vb(a){try{if(q.sessionStorage)return q.sessionStorage[a]}catch(b){}return ma(a)}
function A(a){var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),f=Fd[d];f?x(b,f):x(b,d)}return b.join("")}function Gd(a){a=a.replace(/_/g,"_5F").replace(/%/g,"_25");return A(a)}function O(a){if(a){for(var b=[],c=0;c<a.length;c++){var d=a.charAt(c),f=u,e=l.spc;e||(e="");e+=Hd;-1===f(e,d)&&x(b,d)}a=b.join("")}return a||""}function Wb(){var a=document.location;if(a){var a=a.href,b=u(a,"#");0<=b&&(a=a.substr(0,b));return a}return"-"}function Ia(a,b){a=Math.floor(a);(b||na)&&0<a&&la(oa,a);return a}
function Ja(){return q.performance&&q.performance.timing&&(!v.ff||9<v.ff)?q.performance:null}function Id(a,b,c,d){if(Object.defineProperty&&(!v.ie||8<v.ie)){aa[b]=a[b];var f=function(c){aa[b]=c;d&&d.apply(a,[c]);return aa[b]};try{Object.defineProperty(a,b,{get:function(){return c?c.apply(a,null):aa[b]},set:f,configurable:!0})}catch(e){}}}function Jd(a,b){if(a[b]&&Object.defineProperty&&(!v.ie||8<v.ie)){var c=a[b];try{delete a[b],aa[b]=null,a[b]=c}catch(d){Object.defineProperty(a,b,{get:function(){return aa[b]},
configurable:!0})}}}function Kd(a,b,c,d){if(l.ffi)return!0;for(var f=!1,e=f,g=f,k=0;k<a.length&&(!f||!e);k++)a[k]=a[k].split("."),f=a[k][0]==b,e=a[k][1]==c,!g&&(f&&c>a[k][1])&&(g=!0);a=f&&e||g;if(!f||!e)g?pa(d+" version ("+b+"."+c+") official not supported. Instrumentation active nonetheless, because major version is supported and minor is newer than supported versions."):pa(d+" not instrumented because version ("+b+"."+c+") not supported.");return a}function Ld(a){la("dtUseDebugAgent",a)}function Md(a){la("dt_dbg_console",
a)}function Xb(a){return(0==u(a,"http")||0==u(a,"//"))&&u(location.href,location.host)!=u(a,location.host)}function bb(a){var b=document.createElement("a");b.href=a;return b.cloneNode(!0).href}function ba(){try{return q.location.href}catch(a){}return""}function Nd(a,b,c){return a.apply(b,c)}function Od(a,b,c,d){a=a||{};d=d||"headers";a[d]=a[d]||{};b=b||a.url;if(!Xb(b)){if(a&&(a.actionId||c)){c=c||a.actionId;var f=ba(),h=Yb(c);h&&(qa(a,e.gPCHN(),h,d),Ob()&&(qa(a,"x-dtReferer",f,d),qa(a,"X-Host",Tb(b),
d)));(c=Zb(c))&&c!=f&&qa(a,"x-dtReferer",c,d)}cb(b)&&qa(a,e.gPCHN(),"ignore",d)}return a}function qa(a,b,c,d){c&&(a[d].set?a[d].set(b,c):a[d][b]=c)}function Pb(a){-1<u(a,"^")&&(a=a.split("^^").join("^"),a=a.split("^dq").join('"'),a=a.split("^rb").join(">"),a=a.split("^lb").join("<"),a=a.split("^p").join("|"),a=a.split("^e").join("="),a=a.split("^s").join(";"),a=a.split("^c").join(","),a=a.split("^bs").join("\\"));return a}function Pd(a){return Object.getPrototypeOf?Object.getPrototypeOf(a):{}.__proto__===
Object.prototype&&[].__proto__===Array.prototype?a.__proto__:a.constructor?a.constructor.prototype:void 0}function db(){var a=Qd(!0);if(0<a.length){for(var b=[],c=0;c<a.length;c++)a[c].frameId!==R&&x(b,a[c]);Rd(b)}}function Yb(a){a=R+"h"+e.esc(a);var b=ma(Sd);return b&&0<=u(b,a)&&!e.hyb()?null:a}function Td(a){a=A(a);eb[a]||(eb[a]="1")}function Ud(a){return"1"===eb[a]}function Vd(a,b){if("string"===typeof a)return a===b;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0}function X(){var a=
e;try{for(var b=S;b&&b!==self;){if(b.dT_)return b.dT_.tdto();b=b!==b.parent?b.parent:!1}}catch(c){}return a}function Wd(){return!ra}function $b(a,b,c,d,f){for(var h=3,g=0;0<h;)try{var k,m=l.cors;if(m){var r=Va();"withCredentials"in r||(r=q.XDomainRequest?new XDomainRequest:null);k=r}else k=Va();if(!k)break;g=w();"onreadystatechange"in k?k.open("POST",b,c):k.open("POST",b);"setRequestHeader"in k&&(k.setRequestHeader("Content-Type","text/plain;charset=UTF-8"),f&&!m&&k.setRequestHeader(e.gRHN(),f));
a&&a(k,b,d,g,c);k.send(d);h=0}catch(p){h--}}function ac(a,b){var c;try{c=navigator.sendBeacon(a,b||"")}catch(d){c="Error sending signal via sendBeacon: "+d+": "+a}return c}function bc(){var a=this;a.vals=[];a.a=function(b,c,d){x(a.vals,[b,c,d])};a.an=function(b,c,d){c&&a.a(b,c,d)};a.g=function(b){for(var c=0;c<a.vals.length;c++)if(a.vals[c][0]===b)return a.vals[c][1]};a.s=function(){for(var b=0,c=0;c<a.vals.length;c++)b+=(""+a.vals[c][0]).length+(""+a.vals[c][1]).length+1;return b};a.sts=function(){for(var b=
0;b<a.vals.length;b++)if(a.vals[b][2])return!0;return!1}}function ca(a,b,c,d){sa=!1;a=cc(a,b,c);s&&dc(!!c,!!d,a)}function cc(a,b,c){var d;if(a){var f="";fb=0;var h=!1,g="",k="",m="";for(d in y)if(y.hasOwnProperty(d)){var r=y[d];if(gb(r))h||(h=!0,pa("Maximum open actions exceeded configured amount of "+(l.moa||30)+", dropping action "+r));else{var f=f?f+",":f,p=ec(y[d],!1,!1,!0);p&&!g&&(g=r.getReferer());k=r.getReferer();m=r.getTitle();f+=p}}d={actions:f,referer:g,sourceUrl:k,sourceTitle:m}}else{d=
"";h=B.length;b&&(y=[]);m=k=g="";if(0<h){for(r=0;r<h;r++)if((p=ec(B[r],!0,c,!1))&&0<p.length)g||(g=B[r].getReferer()),k=B[r].getReferer(),m=B[r].getTitle(),"_load_"==B[r].type&&(na=!0,C&&(d=C.delayed?"d|"+C.actionId+"|"+C.name+"|"+C.type+"|"+C.info+"|"+C.frameId+"|"+C.start+"|"+C.location+"|"+C.title:"s|"+C.actionId+"|"+C.name+"|"+C.type+"|"+C.info+"|"+C.frameId+"|"+C.start,k=C.location,m=C.title,C=null)),0<d.length&&(d+=","),d+=p;B=[];for(f in y)y.hasOwnProperty(f)&&x(B,y[f])}d={actions:d,referer:g,
sourceUrl:k,sourceTitle:m}}h=d;g=h.actions;d=h.referer;f=h.sourceUrl;h=h.sourceTitle;s=null;if(0<g.length){s=new bc;s.a("a",ta(g),!0);s.a("fId",R,!1);s.a("v",l.dtVersion,!1);a&&s.a("PV",1,!1);e.pageId!==R&&s.a("pId",e.pageId,!1);hb&&s.a("pFId",hb,!1);s.a("rId",l.rid,!1);s.a("rpId",l.rpid,!1);if(!a){a:{g=(k=Ja())?k.timing:!1;if(k&&g&&(k=g.domComplete,g=g.domContentLoaded,k||g)){g=k?k:g;break a}g=ib}g&&s.a("domR",g,!1);Ka&&na&&(s.a("responseCode",Ka.responseCode,!1),s.an("responseMessage",ta(Ka.message),
!1),Ka=null)}jb(c)&&s.a("unload","xhr",!1);fc(a,b);gc=!1}else!1===gc&&(s||(s=new bc),l.bs&&s.a("bs","1",!1),fc(a,b),s.sts()?(s.a("fId",R,!1),s.a("v",l.dtVersion,!1)):s=null);s&&(a=ba(),s.a("url",encodeURIComponent(a),!1),s.a("title",ta(O(V()).substring(0,100)),!1),((g=(b=s.g("a"))&&("s"===b.charAt(0)||"d"===b.charAt(0)))||b&&-1===b.indexOf("_load_"))&&s.a("vd",w()-ua,!1),f&&(f!=a&&!g)&&(s.a("sUrl",encodeURIComponent(f),!1),s.a("sTitle",h&&h!=V()?ta(O(h).substring(0,100)):"-",!1)),s.an("isUnload",
c,!1),s.an("latC",ma(oa),!1),s.an("app",l.app,!1));return{referer:d}}function fc(a,b){for(var c=0;c<kb.length;c++)kb[c](s,a,b)}function hc(){for(var a=[],b=0;b<s.vals.length;b++)x(a,"$",s.vals[b][0],"=",s.vals[b][1]);return a.join("")}function dc(a,b,c){if(!e.disabled){c=c.referer||ba();c==ba()&&(!l.cors&&!l.bp2)&&(c="");var d=w();s.a("time",d,!1);var f=v,h=!0;(d=a&&ic&&!l.dsndb)||(h=!b&&(!a||!!f.ie&&!Y||!l.lab));a=h;var g,k=c,m=l.cors;b=l.reportUrl?l.reportUrl:"dynaTraceMonitor";var f=[],h=l.bp2,
r=m?"cors":"post",p=[],n={};l.app&&(n.app=l.app);var q=va,t=oa;La()&&h?n[q]=encodeURIComponent(La()):h||(n[q]=encodeURIComponent(La())||"null");n[t]=encodeURIComponent(ma(oa));n.referer=encodeURIComponent(k||"");n.flavor=r;n.type="js";if(h)p=["type",q,"svrid","flavor","referer","visitID"];else if(m||d&&k)p=[q,oa,"referer"];l.app&&x(p,"app");for(g in p)p.hasOwnProperty(g)&&(k=p[g],n[k]&&x(f,k+"="+n[k]));g=f.join(";");h&&(g=f.join("&"));g&&(b+="?"+g);g=b;b=hc();f=[];h=hc();p=jc();h=0===h.length%p?F(h.length/
p):F(h.length/p)+1;if(l.spl||1<h)if(p=jc(),k=w(),m=0,r=l.bp2,1<h){if(100>h)for(q=0;q<h;q++)t="sid="+k+"&p"+(q+1)+"_"+h+"=",r||l.app&&(t="app="+l.app+"&"+t),m+p<=b.length?(n=b.slice(m,m+p),"%"==n.charAt(n.length-1)&&b.length>=m+p+1&&(n+=b.charAt(m+p),n+=b.charAt(m+p+1),m+=2),"%"==n.charAt(n.length-2)&&b.length>=m+p+2&&(n+=b.charAt(m+p),m+=1)):n=b.slice(m),x(f,t+n),m+=p}else f=[b];else f=[b];b=f;for(f=0;f<b.length;f++)h=b[f],d?ac(g,h):$b(Xd,g,a,h,c),ua=w()}}function jc(){var a=3E4;l.msl&&(a=Math.min(a,
F(l.msl)));return a}function Yd(){wa||(wa=document.createElement("doc:rdy"));if(wa.doScroll){var a=function(){try{wa.doScroll("left"),wa=null,ib=w(),L()}catch(b){E(a,0)}};a()}else document.addEventListener("DOMContentLoaded",function(){ib=w();L()},!1)}function Zd(a){da(a)}function da(a){if(sa){var b=!1;a?w()+a<kc&&(b=!0):b=!0;b&&(clearTimeout(lc),sa=!1)}sa||(kc=w()+(a||0),a?(lc=E(ca,a||0),sa=!0):ca())}function lb(a){x(kb,a)}function $d(a,b,c){ca(b,c,!1,a)}function ae(){return!!e.disabled}function L(){for(var a=
0;a<mb.length;a++)mb[a]()}function mc(){return y}function ea(a,b,c,d,f,h,g,k,m,r,p){p=p||{};var n={actionId:be++,start:c,stop:d,type:a,name:b,info:g,domNodes:f,next:[],sendNextPreview:null,previewCountMax:null,parentActionId:null,parentActionLinkType:null,parentFrameActionName:null,simpleName:null,websocketRequestID:h?F(2147483647*Math.random())+1:0,parent:null,referer:p.url||location.href,title:p.title||V(),xhrUrl:k,customAction:m,xhrWrapper:r,getReferer:function(){return n.parent?n.parent.getReferer():
n.referer},getTitle:function(){return n.parent?n.parent.getTitle():n.title},add:function(a){a&&a.name&&x(n.next,a)}};n.timeoutId=E(function(){if(n&&(n.shouldTimeout=!0,!n.stop&&!nb(n))){var a="Action with id "+n.actionId+" '"+n.name+"' timed out! Check full visit for related action. Recorded with version "+e.version;n.xhrWrapper&&(a+=". Readystate: "+n.xhrWrapper.readyState+", xhr url: "+n.xhrUrl+", status: "+n.xhrWrapper.status);pa(a,-1);T(n.actionId)}},1E3*F(l.oat||180));return n}function nb(a){for(var b=
0;b<a.next.length;b++)if(!a.next[b].stop||nb(a.next[b]))return!0;return!1}function nc(){var a=!1,b=[],c;for(c in y)if(y.hasOwnProperty(c)){var d=y[c];0<d.previewCountMax&&(w()>d.sendNextPreview&&(d.sendNextPreview+=6E4,x(b,d)),a=!0)}0<b.length&&ca(!0,!0);for(c=0;c<b.length;c++)b[c].previewCountMax--;a&&E(nc,1E3)}function oc(a,b){if(a)for(var c=null,d=0;d<a.length;d++){c=a[d];if(c.actionId==b)return c;if(c.next&&(c=oc(c.next,b),null!==c))return c}return null}function ob(a){var b=null;B&&(b=oc(B,a));
return b}function Ma(a,b,c,d,f,e,g,k,m,r){c||(c=w());a=ea(b,a,c,null,null,f,e,g,k,m,r);"boolean"==typeof d&&d&&(d=z);if(d){if(b=null,b="number"==typeof d?ob(d):"object"==typeof d?d:z){b.add(a);a.parent=b;pb(a);for(var p in y)y.hasOwnProperty(p)&&(y[p]&&y[p].sendNextPreview>a.start+1E4)&&(y[p].sendNextPreview=a.start+1E4)}}else pb(a),pc(a),x(y,a),z=a,x(B,a),a.sendNextPreview=a.start+1E4,a.previewCountMax=100,E(nc,5E3);return a}function pb(a,b){z!=a&&(z&&(Na=z),(z=a)?ce(a.actionId,b):db())}function T(a,
b,c){b||(b=w());var d=[];if(B)for(var f=0;f<B.length;f++){var e=qc(B[f],a,b,c);"string"!==typeof e&&(d[f]=e)}a=!1;b=[];for(c=0;c<B.length;c++)d[c]?a=d[c]:nb(B[c])||x(b,B[c].actionId);d=[];for(c in y)y.hasOwnProperty(c)&&(f=y[c],0<=Ya(b,f.actionId)?x(d,c):M&&(e=fa.gca(),f.parentActionLinkType=S&&e[e.length-1]==M?"S":"A",M=null));for(c=0;c<d.length;c++)y.splice(d[c],d[c]-(d[c]||NaN)+1||y.length);d=a;da();pb(d,!0)}function qc(a,b,c,d){var f,e,g=a.actionId==b;if(g){a.stop=c;d&&(a.start=d);a.domNodes=
xa(ka("*"));a.timeoutId&&window.clearTimeout&&window.clearTimeout(a.timeoutId);var k=a.parent;if(k&&!k.stop&&k.shouldTimeout){var m=!1;for(e=0;e<k.next.length;e++)if(!k.next[e].stop&&k.next[e].actionId!=b){m=!0;break}m||E(function(){k.stop||T(k.actionId,c)},0)}}else a.stop||(f=a);m=!1;if(a.next&&a.next.length)for(e=1;e<=a.next.length;e++){var r=qc(a.next[a.next.length-e],b,c,d),p="string"===typeof r,m=m||p||r&&r.found===b;p||(f=r||f);if((m||g)&&f)break}if(g||m)"object"===typeof f?f.found=b:f="found";
return f}function ec(a,b,c,d){if(a.parentFrameActionName){var f=[],e=["0"];e[1]=a.parentActionId;e[2]=A(a.parentFrameActionName);e[3]=a.parentActionLinkType;f[0]=e.join("|");f[1]=qb(a,1,b,c,d).result;return!f[1]?null:f.join(",")}return qb(a,1,b,c,d).result||null}function qb(a,b,c,d,f){a.domNodes||(a.domNodes=xa(ka("*")));var h=[];if(a.next&&0<a.next.length){for(var g=0;g<a.next.length;g++){var k=a.next[g],k=qb(k,b+1,c,d,f),m=k.result;if(m)h.push(m);else if(!k.exceeded)return{}}if(c)for(g=0;g<a.next.length;g++)if(k=
a.next[g],k.stop)a.stop&&k.stop>a.stop&&(a.stop=k.stop);else{a.stop=!1;break}}if(!d&&!f&&(!a.stop||0==a.stop))return{};c=[];c[0]=b.toString();c[1]=a.actionId;c[2]=A(a.simpleName||a.name);c[3]=A(a.type);c[4]=a.info?A(a.info):"-";c[5]=a.start;c[6]=a.stop||0;c[7]=a.domNodes;c[8]="-";c[9]="-";c[10]="-";c[11]="-";c[12]="-";c[13]="-";f=8;1==b&&a.childFrameActions&&(c[8]=a.childFrameActions,f=9);a.websocketRequestID&&(c[9]=a.websocketRequestID,f=10);a.xhrUrl&&(c[10]=A(a.xhrUrl),f=11);a.customAction&&(c[11]=
"1",f=12);if(a.xhrUrl){a:{if(b=rc(a.xhrUrl,!0,a.start))if(g=b.startTime,0<g){b=rb(b,["b",Ja().timing.navigationStart+Math.round(g)],!0).join("");break a}b=null}b&&(c[12]=b,f=13);a.xhrUrl&&e.irtx&&e.irtx(a.actionId,a.xhrUrl,a.start,a.stop)}b=document.referrer;"_load_"===a.name&&b&&(c[13]=A(b),f=14);c.splice(f,c.length-f);b=!1;a.stop||d||a.next&&a.next.length||!gb(a)?(h.unshift(c.join("|")),fb++):gb(a)&&(b=!0);a={exceeded:b};1<h.length?a.result=h.join(","):h[0]&&(a.result=h[0]);return a}function gb(a){var b=
F(l.moa)||30,c=["_warning_","_error_","_log_","_rv_","_rs_"];return fb+1>b&&-1==Ya(c,a.type)}function jb(a){if(0<sb||a&&0<P.length)if(a=P.length,0<a)return P[a-1];return null}function cb(a){var b=l.xbp;return!(!b||!b.exec||!a||!b.exec(a))}function sc(a,b,c,d,f,e){if(d&&cb(d))return null;ga&&(Y=!0);var g=null;b||(b=3);var k=U(),m="";k&&(k.info=a||"-",m=k.info);var r=jb(!1);!r&&(k&&k.actionId)&&(r=k.actionId);var p;if(d)a:{var n;try{if(!q.location){p=d;break a}var s=q.location,t=s.origin;if(!t){if(!s.protocol||
!s.host){p=d;break a}t=s.protocol+"//"+s.host}var u=bb(d);n=u.substr(0,t.length+1).toLowerCase()===(t+"/").toLowerCase()?u.substr(t.length):u}catch(v){n=d}n&&(n.length>tc&&n.substr)&&(n=n.substr(0,tc)+"...");p=n}else p=null;d=p;r?g=uc(r,void 0,void 0,void 0,void 0,void 0,d):k?3<=b&&(a={url:k.url,title:k.title},g=tb(k.getName(),k.type,k.start,null,c,m,d,f,e,a),k.actionId=g):z?1<=b&&(g=uc(z.actionId,a,"xhr",w(),c,m,d,f,e)):l.cux&&(g=tb("Unlinked XHR","xhr",w(),null,c,m,d,f,e));return g}function tb(a,
b,c,d,f,e,g,k,m,r){a=Ma(a,b,c,d,f,e,g,k,m,r);a.usage=1;J[a.actionId]=a;return a.actionId}function uc(a,b,c,d,f,e,g,k,m){a=J[a];var r=-1;a?(!a.xhrUrlOverwritten&&(g&&0!=g.indexOf("http"))&&(a.xhrUrl=g,a.xhrUrlOverwritten=!0),a.usage++,r=a.actionId):z&&(r=tb(b,c,d,z.actionId,f,e,g,k,m));return r}function ub(a){try{var b=rc(a);if(b){var c=(b.requestStart-(b.redirectEnd||b.startTime))/2;0<c&&Ia(c);return!0}}catch(d){}return!1}function rc(a,b,c){try{if(a&&K&&K.getEntriesByName){var d=bb(a);0==u(d,"/")?
d=location.protocol+"//"+location.host+d:0!=u(d,"http")&&(d=location.href.substr(0,location.href.lastIndexOf("/")+1)+d);var f=K.getEntriesByName(d);a=null;var e=Number.MAX_VALUE;if(f.length){if(c){for(var g=0;g<f.length;g++){var k=vc(c,f[g]);if(null==a||k<e)a=f[g],e=k}return a}return f[f.length-1]}f=K.getEntriesByType("resource");a=null;e=Number.MAX_VALUE;-1===d.indexOf("?")&&(d+="?");for(g=f.length-1;0<=g;g--)if(0===f[g].name.lastIndexOf(d,0))if(c){if(k=vc(c,f[g]),null==a||k<e)a=f[g],e=k}else return f[g];
return a}}catch(m){}return null}function vc(a,b){return Math.abs(a-(window.performance.timing.navigationStart+Math.round(b.startTime)))}function de(a,b,c,d){c?E(function(){ub(b)},0):ub(b);d=d||w();E(function(){if(!Y){var b=d,c=0;if(c=J[a])c.usage--,c=c.usage,0>=c&&(T(a,b),J[a]=null,delete J[a])}},ee);return 1>=fe()?(L(),!0):!1}function ge(a){a&&J[a]&&(x(P,a),sb++)}function he(a){a&&J[a]&&(sb--,E(function(){for(var b=-1,c=P.length-1;-1==b&&0<=c;)P[c]==a&&(b=c),c--; -1!=b&&(b==P.length-1?P.pop():P.splice(b,
1))},0))}function ie(a){a&&(a.usage=1)}function fe(){var a=0,b;for(b in J)if(b&&J.hasOwnProperty(b))try{a+=J[b].usage}catch(c){}return a}function pc(a){M=null;if(fa){var b=fa.gca();if(M=b[b.length-1])a.parentActionId=M.actionId,a.parentFrameActionName=M.name,M.childFrameActions?M.childFrameActions++:M.childFrameActions=1}}function ya(a,b,c){var d=w();a=O(a);b=ea(b,a,d,d,-1);(c=za(b,c))&&da();return c}function za(a,b){var c;if(c="undefined"==typeof b||null==b?z:ob(b))return c.add(a),!1;pc(a);x(B,a);
return!0}function je(){ya("visit end","_endVisit_",-1)}function ke(a,b){ha<=e.ncv("mepp",10)&&(ha++,ya(a,"_error_",b))}function pa(a,b){ya(a,"_warning_",b)}function le(a,b){ya(a,"_log_",b)}function me(a){a=sc(a,3,!0);return!a?null:ob(a)}function ne(a){return a.websocketRequestID}function oe(a){return a.actionId}function Zb(a){isNaN(a)||(a=J[a]);return a?a.getReferer():null}function pe(a,b){var c=w(),c=ea("_rv_",a+"="+b,c,c,0);za(c);da()}function qe(a,b,c){var d=w();a=ea("_rs_",a+"="+b,d,d,0);za(a,
c);da()}function re(){return z}function wc(){return z?z.name:null}function xc(a){var b=a==wc();if(!Na)return!b;a=a===Na.name&&3E3>=w()-Na.start;return!b&&!a}function se(){return!z||0<z.stop}function te(a){return J[a]}function ue(a,b,c,d,f,e,g){if(4>arguments.length||"undefined"==typeof d)d=!0;return Ma(a,b,c,d,null,f,e,g).actionId}function ve(a,b,c){L();T(a,b,c)}function we(){return na}function xe(a){return a.actionId}function ye(a,b,c){yc(null,null,null,null,a,b,c||!1)}function yc(a,b,c,d,f,h,g){if((a||
f)&&ha+1<=ze){ha++;"string"==typeof f||f instanceof String?(a||(a=f),f={}):f=f||q.event||{};var k=f.message||f.name||f.description||a||f.errorMessage||f.Mb||"Indeterminable error name",m=f.fileName||f.filename||f.sourceURL||f.errorUrl||f.file||b||"",r=f.lineNumber||f.lineno||f.line||f.errorLine||c||-1,p=(f.columnNumber?f.columnNumber+1:void 0)||f.errorCharacter||f.colno||f.column||d||-1,n=zc(f)||Ae(),l=U()||!1,s=f.number||f.code||f.errorCode||-1;q.performance&&window.performance.now?Math.round(q.performance.now()):
e.nw();n&&g&&(n="<wrapper>"+n);if(5011!=s&&(300<k.length&&(k=k.substring(0,300)),g=w(),g=ea("_error_",O(k),g,g,-1),h=za(g,h),g)){m&&(0<=r&&(m+="|"+r),0<=p&&(m+="|"+p),Aa("_location_",m,g));if(n){if(1200<n.length){r=n.split(/(\r\n|\n|\r)/gm);p="";for(n=0;n<r.length&&!(m=r[n].trim(),0<m.length&&(p=250<m.length?p+(m.substring(0,150)+"[...]"+m.substring(m.length-100)+"\n"):p+(m+"\n")),1200<p.length);n++);n=p}r=n.replace("|","^p").replace(/(\r\n|\n|\r)/gm,"|");Aa("_stack_",r,g)}s&&Aa("_code_",s,g);"Indeterminable error name"==
k&&(k=Ba("msg",a),k+=Ba("file",b),k+=Ba("line",c),k+=Ba("column",d),k+=Ba("error",f),Aa("_debug_",k,g));l&&Aa("_useraction_",l.type+"|"+l.getName(),g);h&&da()}}}function Ae(){try{throw Error("");}catch(a){var b=zc(a);if(b&&4<b.split(/\r\n|\r|\n/).length)return"<generated>\n"+b}if((b=v.ie)&&9>b){var b=[],c=0;try{for(var d=arguments.callee.caller.caller;d&&10>b.length;){var f=Be.exec(d.toString());b.push(f?f[1]||"[a]":"[a]");d=d.caller;c++}}catch(e){}if(3<c)return"<generated-ie>\n"+b.join("\n")}return null}
function zc(a){a=a||{};var b=a.stack||a.backtrace||a.stacktrace||!1;return!b&&a.error?a.error.stack:b}function Aa(a,b,c){var d=w();a=ea(a,O(b),d,d,-1);za(a,c.actionId)}function Ba(a,b){var c,d=typeof b;c=""+(a+"|")+(d+"|");if("object"===d)for(var f in b)b.hasOwnProperty(f)&&("stack"!=f&&"error"!=f)&&(c+=f+"|",d=typeof b[f],c+=d+"|","object"!==d&&"function"!==d&&(c+=b[f]+"|"));else c+=b+"|";return c}function vb(a){if(a)for(var b=ka("LABEL"),c=xa(b),d=0;d<c;d++)if(b[d].htmlFor==a)return a=b[d],I(a.innerText,
a.textContent);return null}function I(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];if(c&&"string"==typeof c&&Ha(c))return Ha(c)}return null}function Ac(a){if(a){if(0===u(a,"data:"))return null;a=a.split("/");if(0<a.length)return a[a.length-1].split(".")[0]}return null}function Bc(a){if(a&&a.split){var b=a.split("/");if(0<b.length&&(b=Ha(b[b.length-1]),null!==b))return b}return a}function Cc(a,b){var c=b.nodeName?b.nodeName.toUpperCase():wb,d=b.type&&"string"===typeof b.type?b.type.toUpperCase():
null,f=null;switch(a){case ia.LABEL:c==Ca&&d!=xb&&(c=d&&(d==yb||d==Dc||d==Ec||d==zb)?b.value:null,f=vb(b.id),f=d&&(d==yb||d==Dc||d==Ec)?I(c,f):I(f,c));f||(f=I(b.textContent,b.innerText));break;case ia.NAME:if(c==Ca&&d!=xb||c==yb)f=I(b.name,b.title,d&&d==zb?b.alt:null);break;case ia.OTHER:c==Ca&&d==zb?f=Ac(b.src):c==Fc?f=I(b.title,Bc(b.href)):c==Ce?f=I(b.name,b.title,b.alt,Ac(b.src)):c==De&&(f=I(b.name,b.id,b.action));f||(f=I(b.title,b.data,b.wholeText,b.id));break;case ia.CLASS:f="object"==typeof b.className?
b.baseVal||b.animVal:b.className;break;case ia.TAG:c==Ca&&d!=xb?f=Ca+": "+d:c==Fc?f="LINK":Da||(Da=f=c)}return f}function Gc(a){if(!a)return null;try{if(v.ie&&$a(a))return"VML Node";var b=a.nodeName?a.nodeName.toUpperCase():wb;if(b==Hc||b==Ic||b==Jc||b==Kc)return Da;for(b=0;4>=b;b++){var c=Cc(b,a);if(c&&c!==Da)return c}return Gc(a.parentNode)}catch(d){}return null}function Lc(a,b){if(!b)return null;var c=xa(b);if(0>=c||20<Oa)return null;for(var d=0;d<c;d++){var f=b[d];if(v.ie&&$a(f))return"VML Node";
var e=null;Oa++;if(e=Lc(a,f.childNodes))return e;Oa--;if(e=Cc(a,f))return e}return null}function Ee(a){Da=null;try{if(v.ie&&$a(a))return"VML Node";if("string"==typeof a)return a;if(a.attributes){var b=a.attributes["data-dtname"];b||(b=a.attributes["data-dtName"]);if(b&&b.value)return b.value}var c=a.nodeName?a.nodeName.toUpperCase():wb;if(c==Hc||c==Ic||c==Jc||c==Kc)return"Page: "+Fe;if(c==Mc){var d;if(a){var e=a.nodeName?a.nodeName.toUpperCase():null;if(e!=Mc)d=null;else{var h=vb(a.id),g=I(h,a.name,
e),b=null;if(!a.multiple){var k=a.options&&-1<a.selectedIndex?a.options[a.selectedIndex]:null;k&&(b=I(k.label,k.innerText,k.textContent))}d=b?"["+g+"] to value ["+b+"]":g}}else d=null;return d}if(c==Nc){var m;if(a){var r=a.nodeName?a.nodeName.toUpperCase():null;if(r!=Nc)m=null;else{var p=vb(a.id);m=I(p,a.name,r)||a.nodeName}}else m=null;return m}var n=Ha(I(a.innerText,a.textContent));if(n)return n;Oa=0;if(a.childNodes&&0<xa(a.childNodes))return ia.foreach(Lc,[a])}catch(l){}return Gc(a)}function Oc(a,
b,c,d){if(e!=D)return D.bi(a,b,c,d);try{d||(d=30);var f={id:Ge++,htmlObject:a,name:null,type:b,info:c?c:"-",start:w(),sourceActionCreated:!1,validUntil:w()+d,url:location.href,title:V(),getName:function(){if(!f.name){var a="";(a=l.uam?"dTMasked_"+f.htmlObject.nodeName:O(Ee(f.htmlObject)))||(a="-");var b=l.sl||100;a.length>b&&(a=a.substring(0,b-3)+"...");f.name=a}return f.name},isSourceActionCreated:function(){return f.sourceActionCreated},setSourceActionCreated:function(){var a=f;do a.sourceActionCreated=
!0,a=a.next;while(a)}};Pc&&(f.next=H,f.next&&(f.next.prev=f),H=f);return f}finally{f&&(a=f.validUntil-w(),0>=a?Ab(f):E(function(){Ab(f)},a))}}function U(){if(e!=D)return D.gci();try{if(H){for(var a=H,b=H.next;b;){var c;if(c=b.htmlObject!=a.htmlObject)a:{try{for(var d=b.htmlObject.parentNode;d;){if(d==a.htmlObject){c=!0;break a}d=d.parentNode}}catch(f){}c=!1}c&&(a=b);b=b.next}return a}return null}catch(h){return null}}function Qc(){return e!=D?D.ci():U()?H.getName():null}function He(){return e!=D?
D.cit():U()?H.type:null}function Ie(){return e!=D?D.cih():U()?H.htmlObject:null}function Ea(){return e!=D?D.gpi():Fa}function Rc(){return e!=D?D.pi():Ea()?Fa.getName():null}function Je(){return e!=D?D.pit():Ea()?Fa.type:null}function Sc(){return e!=D?D.piv():Ea()?Fa.validUntil:null}function Tc(){for(var a=H;a;)a.htmlObject=null,a=a.next;H=null}function Ab(a){if(e!=D)return D.ei(a);if(H){for(var b=H;b.next&&b!==a;)b=b.next;b===a&&(Qc()&&(Fa=H),b.htmlObject=null,b.prev?b.prev.next=b.next:H=b.next,b.next&&
(b.next.prev=b.prev))}}function N(a,b,c){var d=!1,e=l.doNotDetect?l.doNotDetect.split(","):null;if(c&&e)for(var h=0;h<e.length;h++)e[h]==c&&(d=!0);d||(b||(b=a),W(document,a,function(a){var c=null;a.target?c=a.target:a.srcElement&&(c=a.srcElement);var d=b;if(("KD"==d||"KU"==d)&&"password"!==c.type)if(a=a.keyCode?a.keyCode:a.charCode)if(l.uam){var e=String.fromCharCode(a);"a"<=e&&"z">=e||("A"<=e&&"Z">=e||"0"<=e&&"9">=e)||(d+=a)}else d+=a;Oc(c,d,null,30)}))}function Ke(a){(Pc=a)||Tc()}function Bb(){var a=
Pa;if(G){var b=G.domLoading;if(!e.syn&&5E3<Math.abs(b-Pa))return Pa;var b=G.redirectStart,c=G.navigationStart,d=G.fetchStart,f=c+6E4;c&&(b?a=f>b?c:b:d&&(a=f>d?c:d))}return Math.floor(a)}function Le(a){a||w()}function Uc(){Z--;if(!Z&&$)for(var a=0;a<Cb.length;a++)try{Cb[a]()}catch(b){}if(0>=Z){var a=G?G.loadEventEnd:0,c;c=G?G.loadEventStart:0;c=c<Bb()?0:c;if($){if(a&&c&&a>c){var d=w()-a;if(5E3<(0>d?-1*d:d))a+=d;T($.actionId,a,c)}else T($.actionId);$=!1}Vc||Wc()}a=X();a!=e&&a.sole()}function Wc(a){if(ja){var b=
0;K&&!a&&(b=G?G.loadEventEnd:0);b?T(ja.actionId,b):T(ja.actionId);ja=null;L()}}function Me(){Wc(1)}function Ne(){Z++}function Oe(){Vc=!0}function Xc(){ja&&!$&&($=Ma("_onload_","_load_",null,ja))}function Yc(a){x(Cb,a)}function Pe(a){x(mb,a)}function Qe(a){x(Db,a)}function Re(){if(!Zc||0<Z)Zc=!0,L(),Uc()}function $c(){L();if(!Eb){var a=X();a!=e&&a.iolm();Xc();Eb=!0;E(Re,0)}}function ad(){"loaded"==document.readyState&&L();"complete"==document.readyState&&$c()}function Fb(){L();Eb||("complete"==document.readyState?
bd?ca(!1,!0):(bd=!0,E(Fb,3E3)):E(Fb,3E3))}function Se(){Gb(!1);var a;if(0<Qa.length){a=ic&&!l.dsndb;for(var b=0;b<Qa.length;b++)try{var c=Qa[b];a?ac(c.path,c.data):$b(null,c.path,!1,c.data)}catch(d){}}if(!cd)try{Tc();a=Q;for(var e=a.length;0<=--e;){var h=a[e];Rb(h.object,h.event,h.handler)}Q=[];K=G=Xa=Wa=null;cd=!0}catch(g){}Ra||(Ra=!0,db())}function Te(){Gb(!0);Ra||(Ra=!0,db())}function Sa(a){l.dsss?ab("dtSa",a):la("dtSa",a)}function Ue(){var a=X().sSAC;a&&a(!1);a=ma("dtSa");l.dsss&&(a=Vb("dtSa"));
for(var b=ka("meta"),c,d=l.mrt||3,f=0;f<b.length&&!c;f++){var h=b[f],g=h.getAttribute("http-equiv");g&&"refresh"==g.toLowerCase()&&(c=(c=h.getAttribute("content"))&&c.split(";"),c=F(c[0])<=d)}c?Z++:Sa("-");a&&"-"!=a&&(b=a.split("|"),10==b.length&&(b={delayed:"true"==b[0],type:b[1],actionId:b[2],name:b[3],info:b[4],start:b[5],frameId:b[6],location:b[7],title:b[8],viewDurationStart:b[9]},c=!1,e!=e.tdto()&&(c=e.tdto().iRO(b.location)),!document.referrer||b.location==A(document.referrer)||b.location==
A(document.location)||c?(C=b,ua=b.viewDurationStart):Sa(a)))}function Hb(a,b,c,d){var e=jb(!0);c=c||w();var h=[];!e&&a&&b&&c?h=["true",A(b),"-1",A(a),A(d||"-"),c,R,A(Wb()),A(O(V()).substring(0,100)),ua]:z&&(h=["false",A(z.type),z.actionId,A(z.name),A(z.info||"-"),c,R,A(Wb()),A(O(V()).substring(0,100)),ua]);return h}function Ve(){var a=null,b=!1;try{var c=function(a){if(a&&a.href)a:{a=a.href.replace(" ","").toLowerCase();for(var b=["javascript:","mailto:"],c=0;c<b.length;c++)if(-1<u(a,b[c])){a=!0;
break a}a=a.split("://");a=!("http"===a[0]||"https"===a[0]||"file"===a[0])}else a=!1;return a},d=function(a){return a?c(a)||d(a.parentNode):!1};if((a=U())&&a.htmlObject&&!Ib){var e=a.htmlObject;if(b=c(e)||d(e.parentNode))Ib=!0,E(function(){Ib=!1},1)}return b}catch(h){return b}}function dd(){Ve()||Gb(!1,!0)}function We(a,b,c){var d=!1;try{d=X().iSAC()}catch(e){}if(!Ta&&!d){a&&(Sa("-"),ed=[]);d=U();if(!d){var h=Ea();h&&(xc(Rc())&&3E3>=w()-Sc())&&(d=h)}var h=[],g=ed;d&&!d.isSourceActionCreated()?(d.setSourceActionCreated(),
h=Hb(d.getName(),d.type,d.start,d.info)):b?h=Hb(null,null,b.start,null):a&&(h=Hb(null,null,c,null));1<g.length&&1<h.length&&g[3]==h[3]&&(g[2]=h[2],g[0]=h[0],h=g);h.length&&(Sa(h.join("|")),(a=X().sSAC)&&a(!0,!0))}}function Gb(a,b){var c=w();if(!ga||Y){a||(ga=!0,E(function(){E(function(){ga=!1;fd(!1);ca(!1,!0,!0);Y=!1},2E3)},1));for(var d=0;d<Db.length;d++)Db[d](ga);var e=null;Y&&B.length&&(e=B[0]);d=cc(!1,!0,!0);We(b,e,c);if(v.sf&&q.frames)for(c=0;c<q.frames.length;c++)try{q.frames[c].dT_&&q.frames[c].dT_.obc()}catch(h){}s&&
dc(!0,!1,d);Y=!1}}function Xe(){return 0>=Z}function Ye(){return Ta}function fd(a,b){Ta=a;clearTimeout(gd);b&&(gd=E(function(){Ta=!1},2E3))}function Ze(a){hd?a(e.bwsW,e.bwsH):x(Jb,a)}function id(){var a=document,b=a.documentElement,c=0,d=0,f=a.body;if("number"===typeof self.innerWidth)c=self.innerWidth,d=self.innerHeight;else if(a&&(b.clientWidth||b.clientHeight))c=b.clientWidth,d=b.clientHeight;else if(f&&(f.clientWidth||f.clientHeight))c=f.clientWidth,d=f.clientHeight;if(0>c||0>d){var h;v.ie?h=
140:h=10;c=Math.max(c,h);d=Math.max(d,10)}a=c;e.bwsW=a;e.bwsH=d;hd=!0;for(b=0;b<Jb.length;b++)Jb[b](a,d)}function $e(){if(!K)return null;var a=K.timing||{},b=K.navigation||{},c=a.navigationStart;return!e.googleBot&&0<c?(b=["a",b.type,"b",c],b=rb(a,b),b.join("")):null}function rb(a,b,c){c=c?a.startTime:a.navigationStart;for(var d in jd){var e=jd[d],h=a[e],g=h&&h>=c;if("u"==d||"v"==d||"w"==d||"x"==d||"y"==d||"A"==d)g="undefined"!=typeof a[e];g&&(b.push(d),"u"!=d&&"v"!=d&&"w"!=d&&"x"!=d&&"y"!=d&&"A"!=
d?b.push(Math.round(h-c)):b.push(h))}return b}var Ga=window;if(!Ga.dT_||Ga.dT_.initialized||!Ga.dT_.ica)Ga.console&&Ga.console.log("Duplicate agent injection detected or no initCode available, turning off redundant core.");else{var q=window,e=q.dT_;e.version=[6,5,24,"1006"];var E=e.st,w=e.nw,F=e.pn,u=e.io,x=e.apush,la=e.sC,ma=e.gC,ta=e.esc,Qd=e.gPC,Rd=e.sPC,kd=e.iVSC,La=e.gSC,ld=e.sSC,ce=e.cPC,af=e.gSSV,bf=e.sSSV,R=e.frameId,ka=e.gEBTN,xa=e.gEL,Sd=e.pageContextCookieName,oa=e.latencyCookieName,va=
e.gSCN(),Pa=e.agentStartTime,ua=Pa,Wa=q.XMLHttpRequest,Xa=q.ActiveXObject,S=q.parent;if(e&&!e.initialized){e.gx=Va;var v=[],t=navigator.userAgent,md=!1,nd=!1;try{var od=/Firefox[\/\s](\d+\.\d+)/,cf=/(iPod|iPhone|iPad)/,df=/AppleWebKit/;if(0<=u(t,"MSIE"))v.ie=F(t.substr(t.lastIndexOf("MSIE")+5,3));else if(0<=u(t,"Trident"))0<=u(t,"rv:")?v.ie=F(t.substr(t.lastIndexOf("rv:")+3,2)):0<=u(t,"rv ")&&(v.ie=F(t.substr(t.lastIndexOf("rv ")+3,2)));else if(0<=u(t,"Edge"))v.edge=F(t.substr(t.lastIndexOf("Edge")+
5,2));else if(0<=u(t,"Android"))v.ab=parseFloat(t.substr(u(t,"Android")+8,3));else if(t.match(cf)&&t.match(df)){var Kb=/Version\/([0-9]*\.[0-9]*)/;t.match(Kb)||(Kb=/OS ([0-9]*_[0-9]*)/);v.msf=parseFloat(t.match(Kb)[1])}else if(("Safari"===navigator.appName||-1<u(t,"Safari"))&&-1===u(t,"Chrom"))v.sf=F(t.substr(t.lastIndexOf("Version/")+8,1));else if(q.opera)v.op=F(q.opera.version().split(".")[0]);else if(0<=u(t,"OPR/"))v.op=F(t.match(/OPR\/([0-9]*\.[0-9]*)/)[1]);else if(od.test(t)){var pd=F(t.match(od)[1]);
v.ff=-1===pd?0:pd}else{var Lb=u(t,"Chrom");-1<Lb&&(v.ch=F(t.substring(Lb+7,Lb+9)))}md=0<u(t,"RuxitSynthetic");nd=0<=u(t,"Googlebot")}catch(ff){}e.gBI=td;e.hyb=Ob;e.syn=md;e.googleBot=nd;var l=e.cfg;Cd();e.acfgP=yd;e.gAN=Bd;e.smbi=vd;e.isc=Ad;e.cfg=xd;e.ism=ud;e.iMod=wd;e.ncv=zd;var Hd="\t\n\r",tc=500,Qb=q.addEventListener,Za=q.attachEvent,Sb=q.removeEventListener,Dd=q.detachEvent,Q=[],Fd={"^":"^^","|":"^p",",":"^c",";":"^s"},aa={};e.tau=bb;e.icr=Xb;e.aIOf=Ya;e.ael=W;e.rel=Rb;e.lv=Vb;e.sv=ab;e.gh=
Tb;e.cvs=Kd;e.esc=ta;e.aesc=A;e.rsc=O;e.tpesc=Gd;e.ulc=Ia;e.gP=Ja;e.apl=Id;e.rpl=Jd;e.dbg=Ld;e.dbc=Md;e.rxapply=Nd;e.loc=ba;e.sch=Od;e.de=Pb;e.gPO=Pd;e.gPAH=Yb;e.pageId=null;e.pageTitle=null;e.frameCount=0;var ra=null,hb,fa,eb={};try{S&&(S!==self&&S.dT_&&Vd(S.dT_.version,e.version))&&(fa=S.dT_,ra=S.dT_.tdto())}catch(gf){}ra?(e.pageId=ra.pageId,e.pageTitle=ra.pageTitle,hb=fa.frameId,fa.frameCount++):(e.pageId=R,e.pageTitle=V());e.tp=Wd;e.tdto=X;e.aFU=Td;e.iRO=Ud;var Xd=function(a,b,c,d,f){function h(a){var c=
w()-d;ub(b)||Ia(c/2);for(var c=a&&a.split("|"),f=1;f<c.length;f++){var g=c[f].split("=");if(g[0]==va||"session"==g[0])g=decodeURIComponent(g[1]),kd(g)&&ld(g);else if("name"==g[0]){g=a;try{if(q.localStorage){var h=l.csu,s=(h.indexOf("dbg")==h.length-3?h.substr(0,h.length-3):h)+"_"+l.app+"_Store",t=q.localStorage.getItem(s),u=Nb(t);Nb(g)>=u&&q.localStorage.setItem(s,g)}}catch(v){}}else"enabled"==g[0]&&"false"==g[1]&&(ab("dtDisabled",!0),e.disabled=!0)}}function g(a){ga&&v.sf&&Qa.push({path:b,data:c})}
"onreadystatechange"in a||(a.onload=function(){h(a.responseText)});a.onreadystatechange=function(){if(a&&4==a.readyState)try{200==a.status?h(a.responseText):g(a.status)}catch(b){g(0)}finally{E(function(){a=null},2)}};if(f&&("timeout"in a&&"ontimeout"in a)&&(f=l.xt))a.timeout=f,a.ontimeout=function(){try{a.abort()}catch(b){}}},ic=navigator&&"sendBeacon"in navigator,s=null,kb=[],sa=!1,ib,gc=!0,wa=!1,lc,kc,Qa=[];e.id=ae;e.ss=$d;e.asl=lb;e.sMPS=Zd;var z=null,Na=null,B=[],y=[],fb=0,sb=0,P=[],J=[],M,na=
!1,Y=!1,ee=v.msf?1E3:0,be=1;e.getCurrentOpenRootActions=mc;var mb=[];e.gid=xe;e.ea=ue;e.la=ve;e.lx=de;e.ex=sc;e.ec=ge;e.lc=he;e.ru=ie;e.eV=je;e.pe=ke;e.pw=pa;e.pl=le;e.rv=pe;e.rs=qe;e.pcn=ya;e.ewa=me;e.gWRI=ne;e.gAID=oe;e.ca=re;e.can=wc;e.isci=xc;e.noa=se;e.ti=L;e.las=we;e.gca=mc;e.gAR=Zb;e.gAA=te;e.sxbe=cb;var Be=/function\s*([\w\-$]+)?\s*\(/i,ha=0;setInterval(function(){0<ha&&ha--},3E4);var ze=e.ncv("mepp",10);e.re=yc;e.rex=ye;var yb="BUTTON",Ca="INPUT",xb="HIDDEN",Dc="SUBMIT",Ec="RESET",zb="IMAGE",
Ce="IMG",Fc="A",De="FORM",Kc="#DOCUMENT",Hc="HTML",Ic="BODY",Jc="HEAD",Mc="SELECT",wb="unknown",Nc="TEXTAREA",Fe=Bc(ba()),Da=null,ia={LABEL:0,NAME:1,OTHER:2,CLASS:3,TAG:4,foreach:function(a,b){for(var c=0;4>=c;c++){var d=a(c,b);if(d)return d}return null}},Oa=0,H,Fa=null,Ge=0,Pc=!0,D=e.tdto();N("click","C","clk");N("mousedown","D","mdw");N("mouseup","U","mup");N("dblclick","CC","dcl");N("keydown","KD","kyd");N("keyup","KU","kyu");N("scroll","S","scr");N("touchstart","TS","tcs");N("touchend","TE","tce");
if(l.ade){var Ua=l.ade.split(",");if(Ua&&0<Ua.length)for(var Mb=0;Mb<Ua.length;Mb++)N(Ua[Mb])}e.bi=Oc;e.ei=Ab;e.gci=U;e.ci=Qc;e.cit=He;e.cih=Ie;e.gpi=Ea;e.pi=Rc;e.pit=Je;e.piv=Sc;e.aad=Ke;var Eb=!1,Zc=!1,bd=!1,Z=1,C=null,ed=[];Ue();var $=null,Ra=!1,Cb=[],Db=[],ga=!1,cd=!1,Ka=null,qd=document.location;qd&&e.tdto().aFU(qd.href);l.rid||(l.rid=Ed(l.ridPath));var G=null,Vc,Ta=!1,gd=-1,K=Ja();K&&(G=K.timing)&&Ia((G.requestStart-(G.redirectEnd||G.navigationStart))/2,!0);e.sls=Le;e.sole=Uc;e.iolm=Ne;e.solb=
Xc;e.slem=Oe;e.lst=Bb;var Ib=!1;W(q,"beforeunload",dd);W(q,"unload",Se);W(q,"pagehide",Te);W(document,"readystatechange",ad);E(Fb,3E3);W(q,"load",$c);Yd();if(!window.doNotCreateLoadAction){var ja=Ma("_load_","_load_",Bb(),null);L();ad()}e.all=Yc;e.ail=Pe;e.apll=Qe;e.sle=Me;e.obc=dd;e.ile=Xe;e.iSAC=Ye;e.sSAC=fd;var Jb=[],hd=!1;Yc(id);e.abwsl||(e.abwsl=Ze);var rd=!1;lb(function(a,b,c){if(!b&&!rd&&(na||c))rd=!0,c=X(),b=c.bwsW||e.bwsW,c=c.bwsH||e.bwsH,b||(id(),b=e.bwsW,c=e.bwsH),a.a("w",0>b||2147483647<=
b||isNaN(b)?0:b,!0),a.a("h",0>c||2147483647<=c||isNaN(c)?0:c,!0)});lb(function(a,b){if(!l.disableCookieManager){var c=La();try{if(q.sessionStorage){var d=af(va)||"";kd(d)||(d="");if(d&&"null"!=d&&c!=d){var f,h=d;if(h){var g=u(h,"|");-1!=g&&(h=h.substring(0,g))}f=h;if("undefined"!=typeof c&&""!=c&&(d=c)&&f)var k=u(d,"|"),d=-1!=k?f+d.substring(k):f;c=d}c&&(e.dC(va),ld(c),bf(va,c))}}catch(m){}}});var jd={c:"redirectStart",d:"redirectEnd",e:"fetchStart",f:"domainLookupStart",g:"domainLookupEnd",h:"connectStart",
i:"connectEnd",j:"secureConnectionStart",k:"requestStart",l:"responseStart",m:"responseEnd",n:"domLoading",o:"domInteractive",p:"domContentLoadedEventStart",q:"domContentLoadedEventEnd",r:"domComplete",s:"loadEventStart",t:"loadEventEnd",u:"transferSize",v:"encodedBodySize",w:"decodedBodySize",x:"statuscode",y:"ip",A:"failedImage"},sd=!1;l.ntd||e.asl(function(a,b){if(!b&&!sd&&e.las())if(sd=!0,"undefined"!=typeof K)if(v.ff&&9>=v.ff)a.a("nt","0");else{var c=$e();c?a.a("nt",c):a.a("nt","0")}else a.a("nt",
"0")});e.snt=rb;var ef={setAutomaticActionDetection:function(a){dT_.aad(a)},setLoadEndManually:function(){dT_.slem()},signalLoadStart:function(a){dT_.sls(a)},signalLoadEnd:function(){dT_.sle()},sendSignal:function(a,b,c){dT_.ss(a,b,c)},enterAction:function(a,b,c,d){return dT_.ea(a,b,c,d)},leaveAction:function(a,b,c){dT_.la(a,b,c)},reportError:function(a,b){dT_.rex(a,b)},reportWarning:function(a,b){dT_.pw(a,b)},reportEvent:function(a,b){dT_.pl(a,b)},reportValue:function(a,b){dT_.rv(a,b)},reportString:function(a,
b){dT_.rs(a,b)},tagVisit:function(a){dT_.rs("dt_visittag",a)},startThirdParty:function(a,b){dT_.tpstr&&dT_.tpstr(a,b)},stopThirdParty:function(a,b,c,d){dT_.tpsto&&dT_.tpsto(a,b,c,d)},addPageLeavingListener:function(a){dT_.apll(a)},addStreamingNode:function(a,b,c,d,e,h,g,k,m){var l=[],p=0;l[p++]=a;l[p++]=b;l[p++]=!0===c?1:0;l[p++]=!0===d?1:0;l[p++]=e;l[p++]=h;l[p++]=g;l[p++]=k;a=l.join("|");dT_.pcn(a,m,null)},beginUserInput:function(a,b,c,d){return dT_.bi(a,b,c,d)},endUserInput:function(a){dT_.ei(a)},
enterXhrAction:function(a,b,c){return dT_.ex(a,b,c)},leaveXhrAction:function(a){dT_.lx(a)},enterXhrCallback:function(a){dT_.ec(a)},leaveXhrCallback:function(a){dT_.lc(a)},signalOnLoadStart:function(){dT_.solb()},incrementOnLoadEndMarkers:function(){dT_.iolm()},signalOnLoadEnd:function(){dT_.sole()},endVisit:function(){dT_.eV()},setAppVersion:function(a){dT_.rs("dt_appversion",a)},setMetaData:function(a,b){dT_.sMD&&dT_.sMD(a,b)}};"undefined"!=typeof dT_&&"undefined"==typeof window.dynaTrace&&(window.dynaTrace=
ef);e.initialized=!0;"function"==typeof e.initCallback&&e.initCallback()}}})();
(function(){function r(a,c,d){for(var f=2;f<arguments.length;f++)a.push(arguments[f]),(f<arguments.length-1||c)&&a.push("|")}function U(a,c){return a[12]<c[12]?1:a[12]==c[12]?0:-1}function V(a,l){for(var d=c.nw(),f=0;f<s.length;f++)if(s[f][1]==l)return;var f=c.ca(),h={};h[0]=a;h[3]=d;h[4]=0;h[1]=l;h[2]=f?f.name:"-";h[9]=!1;r(s,0,h)}function W(a,l,d,f){for(var h=0;h<s.length;h++){var e=s[h];if(e[1]==a){2<arguments.length&&0<d&&(e[3]=d);e[4]=3<arguments.length&&0<f?f:c.nw();e[7]=l;l||(e[9]=!1,e[10]=
!0);break}}}function X(a){if(c.re_t)for(var l=0,l=0;l<a.length;l++){var d=a[l];0===d[4]&&0<d[3]&&("i"===d[0]?(d[8]=!0,d[7]=!1,d[4]=c.nw()):(d[5]||(d[7]=!0),d[4]=d[3]));d[12]=d[4]?d[4]-d[3]:d[12]}}function H(a,l){var d=c.lst();X(a);if(0<a.length&&0<d){var f={},h;for(h=0;h<a.length;h++){var e=a[h],p=c.gh(e[1]);p&&0<p.length&&(f[p]||(f[p]=[]),r(f[p],0,e))}var q={},n=null;for(n in f)if(f.hasOwnProperty(n)&&f[n].length){p=f[n];p.sort(U);var k={};for(h=0;h<p.length;h++){var e=p[h],b=k[e[0]];b||(b={successful:0,
interrupted:0,failed:0,cached:0,withImpact:0,withNetworkTiming:0,impactIntervals:new N,w3cIntervals:new N,avgImpact:0,minImpact:d+99999999,maxImpact:0,avgNetworkTime:0,minNetworkTime:d+99999999,maxNetworkTime:0},k[e[0]]=b);if(e[3]&&e[4]){b.withImpact++;var g=e[4]-e[3];b.minImpact=b.minImpact<g?b.minImpact:g;b.maxImpact=b.maxImpact>g?b.maxImpact:g;b.avgImpact=c.pn((b.avgImpact*(b.withImpact-1)+g)/b.withImpact,10);b.impactIntervals.add(e[3]-d,e[4]-d)}if(e[5]&&e[6]){b.withNetworkTiming++;g=e[11];0>g&&
(g=e[6]-e[5]);if(0>g||3E5<g)g=0;b.minNetworkTime=b.minNetworkTime<g?b.minNetworkTime:g;b.maxNetworkTime=b.maxNetworkTime>g?b.maxNetworkTime:g;b.avgNetworkTime=c.pn((b.avgNetworkTime*(b.withNetworkTiming-1)+g)/b.withNetworkTiming,10);b.w3cIntervals.add(e[5],e[6])}b.successful+=e[7]?1:0;b.cached+=e[9]?1:0;e[7]||(b.interrupted+=e[8]?1:0,b.failed+=e[8]?0:1)}q[n]={maxDuration:0};for(var m in k)k.hasOwnProperty(m)&&(b=k[m],q[n].maxDuration=Math.max(b.maxImpact,b.maxNetworkTime),q[n][m]="i"==m||"s"==m?[b.successful,
b.failed,b.interrupted,b.cached,b.withImpact,b.withNetworkTiming,b.impactIntervals.getIntervalsAsString(),b.avgImpact,b.withImpact?b.minImpact:"0",b.maxImpact,b.w3cIntervals.getIntervalsAsString(),b.avgNetworkTime,b.withNetworkTiming?b.minNetworkTime:"0",b.maxNetworkTime].join("|"):"o"==m||"y"==m?[b.successful,b.failed,b.interrupted,b.cached,b.w3cIntervals.getIntervalsAsString(),b.avgNetworkTime,b.minNetworkTime,b.maxNetworkTime].join("|"):[b.successful,b.impactIntervals.getIntervalsAsString(),b.avgImpact,
b.minImpact,b.maxImpact].join("|"))}m=[];for(n in q)f.hasOwnProperty(n)&&r(m,0,n);0<w&&(p=m.sort(function(a,b){return q[b].maxDuration-q[a].maxDuration}),p.length>w&&(m=p.slice(0,w)));k=[];for(b=0;b<m.length;b++){n=m[b];p=f[n];h=q[n];0<k.length&&r(k,0,";");r(k,1,c.aesc(n),"featureHash");e=0;n=k.length-2;h.i&&(r(k,1,h.i),e+=2);h.s&&(r(k,1,h.s),e+=4);h.y&&(r(k,1,h.y),e+=8);h.o&&(r(k,1,h.o),e+=16);h.c&&(r(k,1,h.c),e+=32);k.pop();k[n]=e.toString(32);for(h=0;h<p.length&&h<I&&(p[h][12]>=J||p[h][11]>=J);h++)e=
p[h],r(k,0,","),r(k,0,e[0]+(e[7]?"":e[8]?"i":"f"),e[3]?e[3]-d:0,e[4]?e[4]-d:0,c.aesc(e[2]),c.tpesc(e[1])),e[5]&&r(k,0,"",e[5],e[6])}if(0>=k.length)return null;f=k.join("");l&&(f=l+"-"+d+";"+f);return c.esc(f)}return null}function Y(a,l,d){if(!l&&c.las()&&(!c.syn||d))if(c.re_t&&c.gIA&&!O)if(c.gIA()&&!d)c.sMPS(1E3);else{O=!0;var f=H(s);f&&a.a("3p",f,!0);s=[]}else if(c.re_r&&c.gSig&&(D=K("navigationStart"),!(0>=D)))if(l=K("loadEventEnd"),!d&&(0>=l||c.nw()-l<Z))c.sMPS(2E3);else{if(l=$())w=-1,I=0,E=1;
d=c.gSig(d);var h=[],e=[];if(d&&0<d.length)for(var p=0;p<d.length;p++){var f=d[p].actionId,q=d[p].resources;if(c.gBI().op)for(var n=q,q=[],k=[],b=0;b<n.length;b++){var g=n[b];k[g.name]||(q.push(g),k[g.name]=!0)}c.aai&&c.aai(q);n=[];for(k=0;k<q.length;k++){b=n;g=q[k];try{var m={};m[0]=aa(g);m[11]=g.duration?Math.round(g.duration):0;m[5]=P(g);var v=m,u;if(0<g.responseEnd){var z=D+g.responseEnd,z=z-c.lst();u=Math.round(z)}else z=c.nw(),u=Math.round(z-c.lst());v[6]=u;m[1]=g.name;var y=A.timing.loadEventEnd;
m[2]=P(g)<=y?"_load_":"-";m[8]=0===g.responseEnd;m[7]=g.failedImage?!1:c.gh(g.name)==F&&c.gBI().ie?0!=g.requestStart:0<g.responseEnd;m[9]=c.gBI().ch?0!=g.domainLookupStart&&0==g.requestStart:c.gh(g.name)!=F&&0===g.requestStart&&2>g.duration?!0:0>=g.responseEnd?!1:g.requestStart==g.fetchStart&&g.requestStart==g.responseStart&&g.responseStart!=g.responseEnd;b.push(m)}catch(C){}}n=n.concat(s);s=[];if(l){b=q;q=f;k=K("navigationStart");if(0>=b.length||0>=k)q=null;else{g=[];m=!0;for(v=0;v<b.length&&!(v==
L&&0!=v);v++){var B=b[v],t=B.startTime;if(0<t||B.failedImage){B=c.snt(B,t?["b",Math.round(t)]:[],!0);m||r(g,0,"|");m=!1;t=b[v].name;if(0==M||t.length>x&&2==M)t=t.split("?")[0];var G=x;t.length>x&&("%"==t.charAt(x-1)?G--:"%"==t.charAt(x-2)&&(G-=2));r(g,0,c.tpesc(t.substring(0,G)),B.join(""))}}b=g.join("");b=q?q+"-"+k+";"+b:"-"+k+";"+b;q=c.esc(b)}q&&e.push(q)}(f=H(n,f))&&h.push(f)}else 0<s.length&&(f=H(s))&&h.push(f);Q(a,h,"3p");Q(a,e,"rt")}}function Q(a,c,d){if(0<c.length)for(var f=0;f<c.length;f++)a.a(d+
(0<f?f:""),c[f],!0)}function $(){if(1E4==y)return!0;var a=c.gDtc();if(a){for(var l=0,d=0;d+1<a.length;d+=2)var f=a.charCodeAt(d),h=a.charCodeAt(d+1),l=l+(""+(f+h));return Math.floor(Math.abs(1E7*Math.sin(l)))%1E4<y}return!1}function ba(a){var l=c.gh(a),d=-1!=a.indexOf("chrome-extension://")||-1!=a.indexOf("chrome://")||-1!=a.indexOf("data:")||-1!==a.indexOf("res://");a=-1!==a.indexOf("://localhost/")||-1!==a.indexOf("://localhost:")||l&&-1!==l.indexOf(R,l.length-R.length);return E?!d:!d&&!a&&l&&l!=
F}function aa(a){a=a.name.toLowerCase();-1<a.indexOf("ScriptResource.axd")?a="js":(a=a.substr(1+a.lastIndexOf("/")),0<a.indexOf("?")&&(a=a.split("?")[0]),0<a.indexOf("#")&&(a=a.split("#")[0]),a=0<a.indexOf(".")?a.substring(a.lastIndexOf(".")+1):"-");switch(a){case "js":return"s";case "gif":case "png":case "jpg":case "jpeg":case "ico":case "tiff":case "bmp":case "xbm":case "svg":return"i";case "css":return"y";default:return"o"}}function K(a){return A&&A.timing?A.timing[a]:-1}function P(a){a=D+a.startTime;
a-=c.lst();return Math.round(a)}var c=window.dT_,A,D=null,O=!1,J=500,I=3,Z=3E3,E=!0,w=-1,y,L,x,M,F,R=".local",N=function(){this.head=null;this.add=function(a,c){if(!(a>c)){var d={start:a,stop:c},f=this.head,h=null;if(f){for(;f&&a>f.start;)h=f,f=f.next;h?(d.next=h.next,h.next=d):(d.next=this.head,this.head=d)}else this.head=d,d.next=null}};this.reduce=function(){for(var a=this.head;a&&a.next;){for(;a.next&&a.stop+1>=a.next.start;)a.stop<=a.next.stop&&(a.stop=a.next.stop),a.next=a.next.next;a=a.next}};
this.getIntervalsAsString=function(){this.reduce();for(var a=[],c=this.head;c;)0<a.length&&r(a,0,"_"),r(a,0,c.start),r(a,0,"_"),r(a,0,c.stop),c=c.next;return a.join("")}},s=[];if(c&&(c.smbi("2")||c.syn&&!c.tpih)){A=c.gP();var S=200,T=1,u=(c.cfg("tp")?c.cfg("tp"):"500,50,3").split(","),C=u.length;if(!(3>C||5<C)){J=c.pn(u[0],10);I=c.pn(u[2],10);4<=C&&(E=c.pn(u[3],10));5<=C&&(w=c.pn(u[4],10));if(y=c.ncv("rt",0))L=c.ncv("rtl",100),x=c.ncv("rtu",S),M=c.ncv("rtp",T);c.syn&&(y=1E4,L=0,S=200,T=2,w=-1,E=!0);
F=c.gh(c.loc());c.tpih=ba;c.tpstr=V;c.tpsto=W;c.asl(Y)}}})();
(function(){function s(b){a.tpsto(b.target.src,!0)}function t(){window&&(window.event&&window.event.srcElement)&&("loaded"==window.event.srcElement.readyState||"complete"==window.event.srcElement.readyState)&&a.tpsto(window.event.srcElement.src,!0)}function l(){for(var b=document.getElementsByTagName("script"),c=a.gEL(b),e=0;e<c;e++)try{var d=b[e];if(!d.dtInstrTime&&(d.dtInstrTime=a.nw(),""!=d.src&&a.tpih(d.src)&&(!d.attributes||!d.attributes["data-dtconfig"])))a.tpstr("s",d.src),a.gBI().ie&&11>a.gBI().ie?
a.ael(d,"readystatechange",t):a.ael(d,"load",s)}catch(f){}}function u(b){var c=null;b?b.target?c=b.target:b.srcElement&&(c=b.srcElement):window&&window.event&&(c=window.event.srcElement);c&&a.tpsto(c.src,!0)}function v(b){var c=null;b?b.target?c=b.target:b.srcElement&&(c=b.srcElement):window&&window.event&&(c=window.event.srcElement);c&&c.src!=a.loc()&&a.tpsto(c.src,!1)}function m(b){if(!b.dtInstrTime){b.dtInstrTime=a.nw();try{if(""!=b.src&&a.tpih(b.src)){a.tpstr("i",b.src);var c;c=b.complete?"undefined"!=
typeof b.naturalWidth&&0===b.naturalWidth?!1:!0:!1;c?a.tpsto(b.src,!0):(a.ael(b,"load",u),a.ael(b,"error",v))}}catch(e){}}}function n(){var b=document.getElementsByTagName("img"),c=a.gEL(b),e,d;for(e=0;e<c;e++)d=b[e],m(d);b=document.getElementsByTagName("input");c=a.gEL(b);for(e=0;e<c;e++)d=b[e],d.type&&"SUBMIT"==d.type.toUpperCase()&&m(d)}function p(){0<g&&2E3<a.nw()-g?(h=!1,a.sMPS(5E3)):(a.re_t&&(n(),l()),a.st(p,q))}function r(){a.tpsto?(n(),l(),a.ca()&&!h&&(g=a.nw(),h=!0,p())):a.st(r,1)}function w(){return h}
var a=window.dT_,q=30,g,h;if(a&&a.smbi("3")){var f=(a.cfg("tp")?a.cfg("tp"):"500,50,3").split(","),k=f.length;3<=k&&5>=k&&(q=a.pn(f[1],10));a.re_t=!0;if((f=a.gP())&&f.timing)if(k=f.getEntriesByName||f.webkitGetEntriesByName,(f.getEntriesByType||f.webkitGetEntriesByType)&&k)a.re_t=!1;a.re_t&&(a.gIA=w,a.all(function(){g=a.nw()}),a.asl(function(){-1===g&&(g=a.nw())}),g=-1,r())}})();
(function(){function r(a,e){if(!a)return{x:-1,y:-1};var b={};if(a.getBoundingClientRect){var d=a.getBoundingClientRect();b.x=d.left;b.y=d.top}else document.getBoxObjectFor?(d=document.getBoxObjectFor(a),b.x=d.x,b.y=d.y):(b.x=-1,b.y=-1);e&&window.self!=window.top&&(d=n(),d=s(d),b.x+=d.x,b.y+=d.y);return b}function t(){c.gEL(document.images)>k&&z();u||c.st(t,10)}function z(){for(var a=document.images,e=c.gEL(a),b=0===k?0:k-1;b<e;b++)a[b].complete?c.abwsl(function(a,b){return function(){v(a,b)}}(a[b],
c.nw())):A(a[b]);k=e}function A(a){c.ael(a,"load",p);c.ael(a,"error",p);c.ael(a,"abort",p)}function p(a){var e=a.target||a.srcElement,b=c.nw();c.abwsl(function(){v(e,b)})}function v(a,e){if(c!=f)f.abwsl(function(){var b=r(a,!0),d=q(a,b),d=d&f.iws(a,b);f.aCR(d,e,a&&a.src||"")});else{var b=q(a),d="";a&&(d=c.io(a.src,"data:")?a.src||a.alt||"":a.alt||"data-image");w(b,e,d)}}function w(a,e,b){a&&c.vi++;a&&e>g&&(l=b,g=e)}function q(a,e){if(!a)return!1;e||(e=r(a));if(0<=e.x&&5>=e.x&&0<=e.y&&5>=e.y)return!0;
var b=f.bwsW,d=f.bwsH,c=a.width||a.scrollWidth,m=a.height||a.scrollHeight;if(0>=e.x&&0>=e.y&&0<=e.x+c&&0<=e.y+m)return!0;if(0>c||0>m||0>b||0>d)return!1;var g=B,h=C,k=e.x,l=e.y,c=c+k,m=m+l,b=b+g,d=d+h;return(c<k||c>g)&&(m<=l||m>=h)&&(b<g||b>k)&&(d<h||d>l)}function x(){var a=c.gP();a&&(a.timing&&!h)&&(h=a.timing.loadEventEnd);0===h&&(h=c.nw());return h}function D(){u=!0;var a=x();if(0===g||0===document.images.length)g=a}function s(a){for(var c=0,b=0,d=window.self;null!==d&&f!=d.dT_;){c+=a?a.offsetLeft:
0;b+=a?a.offsetTop:0;try{a=n(window.parent),d=d.parent}catch(g){d=null}}a={};a.x=c;a.y=b;return a}function n(a){a||(a=window);if(f===c)return null;try{for(var e=a.parent.frames,b=0;b<e.length;b++){var d=e[b];if(d==a)return d.frameElement}return null}catch(g){return null}}function E(){if(!c.bwsW||!c.bwsH||!l)return!1;if(c===f)return!0;var a=n();return null===a?0<c.vi||0===window.frames.length:0===c.vi||0===c.gEL(document.images)&&0<window.frames.length?!1:f.iws(a,s(a))}var c=window.dT_,B=0,C=0,u=!1,
k=0,g=0,l="",h=c.vi=0,f=null;c.aCR=w;var y=!1;c&&c.smbi("p")&&(c.iws=q,f=c.tdto(),t(),"iws"in f&&(c.all(D),c.asl(function(a,e,b){if(!e&&!y&&(c.las()||b)){y=!0;e=c.lst();b=x();var d=g-e;0>=d&&(d=b-e);if(0>d||2147483647<=d)d=0;e=d;E()&&a.a("p",e+(l?"|"+c.esc(l):""),!0)}})))})();
(function(){function h(a,d,b,k,q){var l=!1;if(!e&&!m){m=!0;try{try{f&&(f!=h&&"function"==typeof f)&&(l=f(a,d,b,k,q))}catch(s){c.rex(s,null,!0)}l||c.re(a,d,b,k,q)}catch(g){}m=!1}return l}function r(a,c,b){a[c]=b(a[c])}function n(a,d){try{if(!p(a))return a;a.rxewrapper||(a.rxewrapper=function(k){if(g)try{if(p(a))return a.apply(this,arguments)}catch(b){throw c.rex(b,null,!0),t(),b;}finally{}else if(p(a))return a.apply(this,arguments)},a.rxewrapper.rxewrapper=a.rxewrapper);return a.rxewrapper}catch(b){return a}}
function t(){e+=1;c.st(function(){e-=1})}function p(a){return"[object Function]"==Object.prototype.toString.call(a)}function u(){d.onerror!=h&&(c.rxehandler=h,d.onerror&&(f=d.onerror),d.onerror=c.rxehandler);try{c.apl(window,"onerror",function(){return h},function(a){f=a})}catch(a){}c.ael(d,"unload",function(){c.rpl(window,"onerror");d.onerror=null});if(window.atob){if(window.ErrorEvent)try{0===(new window.ErrorEvent("test")).colno&&(g=!1)}catch(e){}}else g=!1;c.gBI().msf&&(g=!0);if(g){var b=document.getElementsByTagName("html");
(0==b.length||0<b.length&&!b[0].hasAttribute||0<b.length&&!b[0].hasAttribute("webdriver"))&&"EventTarget Window ModalWindow".replace(/\w+/g,function(a){if((a=window[a]&&window[a].prototype)&&a.hasOwnProperty&&a.hasOwnProperty("addEventListener"))r(a,"addEventListener",function(a){return function(c,b,d,e){b&&b.handleEvent&&(b.handleEvent=n(b.handleEvent,{eventHandler:!0}));return a.call(this,c,n(b,{eventHandler:!0}),d,e)}}),r(a,"removeEventListener",function(a){return function(b,c,d,e){a.call(this,
b,c,d,e);return a.call(this,b,n(c),d,e)}})})}}var d=window,c=d.dT_,f,m=!1,e=0,g=!0;c&&c.smbi("q")&&u()})();
(function(){function v(b,d,c,f){for(var e=0;e<g.length;e++)if(g[e].actionId==b)return;g.push({type:"x",url:d,actionId:b,start:c,stop:f,resources:[]});a.sMPS(5E3)}function p(){var n=[],d;try{var c,f,e;if(c=document.getElementsByTagName("iframe"))for(f=0;f<c.length;f++)try{var h=c[f].contentWindow.performance.getEntriesByType("resource");if(h)for(e=0;e<h.length;++e)d=h[e],r[d.name+d.startTime+d.responseEnd]||n.push(d)}catch(s){}}catch(t){}try{var k=b.getEntriesByType("resource");for(c=0;c<k.length;++c)d=
k[c],r[d.name+d.startTime+d.responseEnd]||n.push(d);for(k=0;k<n.length;k++)try{d=n[k];var l=d.name;c=a.res[l]=d;var w=c.name;if(!(a.gh(c.name)==a.gh(a.loc())&&a.gBI().ch&&c.domainLookupStart<c.fetchStart||-1<w.indexOf(a.gAN()))&&!(-1<w.indexOf(a.cfg("reportUrl"))||-1<w.indexOf("js.ruxit.com")||c.startTime>c.responseEnd)){var x;a:{c=l;for(f=0;f<g.length;f++)if(c&&-1<c.indexOf(g[f].url)){x=!0;break a}x=!1}if(!x&&a.tpih(l)){c=d;f=null;e=void 0;for(var p=b&&b.timing?b.timing.navigationStart:-1,u=b&&b.timing?
b.timing.loadEventEnd:-1,y=p+c.startTime,h=0;h<g.length;h++){var m=g[h],q="l"==m.type?p:m.start,v="l"==m.type?u:m.stop,A=y-q;if(q<=y&&y<=v+z&&(null==f||e>A))f=m,e="l"==m.type?0:A}f&&(f.resources.push(c),r[c.name+c.startTime+c.responseEnd]=!0)}}}catch(B){}}catch(C){}finally{k=b.getEntriesByType("resource"),900<k.length&&(D(),r={})}}function D(){try{"function"===typeof s&&s.call(b),a.st(function(){t.call(b)},0)}catch(n){}}function B(b){p();for(var d=0,c=[],f=0;f<g.length;f++){var e=g[f],h=e.stop;a.nw()>
h+12E4?d++:(C(e.resources),b||a.nw()>(e.stop?e.stop:e.start)+2E3?(0>=e.resources.length||c.push({actionId:e.actionId,resources:e.resources}),d++):a.st(function(){a.sMPS(2E3)}))}g=g.slice(d);return c}function C(b){if(a.gFI){var d=a.gFI();Array.prototype.push.apply(b,d)}}function E(){u=b.getEntriesByType;q=b.getEntriesByName;l=b.setResourceTimingBufferSize;t=b.clearResourceTimings;var a=function(){};b.clearResourceTimings&&(b.clearResourceTimings=a);b.webkitClearResourceTimings&&(b.webkitClearResourceTimings=
a);return u&&q&&l&&t}function F(a){"function"===typeof b.addEventListener?b.addEventListener("resourcetimingbufferfull",a):"undefined"!==typeof b.onresourcetimingbufferfull&&(s=b.onresourcetimingbufferfull,b.onresourcetimingbufferfull=a)}var a=window.dT_,b,l,u,q,t,s,g=[],r={},z=1E3;if(a&&a.smbi&&(a.smbi("r")||a.syn&&!a.re_r))b=a.gP(),a.res={},window.externalHost?a.re_r=!1:b&&b.timing&&E()?(a.re_r=!0,l.call(b,1E3),a.syn||(z=a.ncv("rtt",z)),a.irtx=v,a.gSig=B,F(p),g.push({type:"l",start:a.lst(),resources:[]})):
a.re_r=!1})();
